[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Enterprise WiFi and Firebase setup

lib_deps = 
    mikalhart/TinyGPSPlus @ ^1.0.3
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.14
    bblanchon/ArduinoJson @ ^7.0.0
    ;mature ESP32 Firebase library, supporting RTDB,
    ;Firestore, FCM, and Storage. 
    ;It uses the Firebase REST API under the hood, 
    ;which means it doesn't maintain a persistent WebSocket 
    ;like the JS SDK — each write is an HTTPS request.